from kivy.app import App 
from kivy.uix.gridlayout import GridLayout 
from kivy.uix.label import Label
from kivy.uix.image import Image
from kivy.uix.button import Button 
from kivy.uix.textinput import TestInput

class SayHello(App):
    def build(self):
        self.Label = ('Kivy App')
        self.Window = GridLayout()
        # add widgets to window
        return self.Winddow
if __name__=='__main__':
    SayHello().run()